env: production
web_instances: 1
web_memory: 256M
services:                                                                                                                                                                          │ `3]{--ضKgyLVG{>,0̨̩̪+/$(k#'g
  - clubfed-rds-production
